# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# every third number is a even number

f = ->(x){ x < 2 ? x : f[x-1] + f[x-2] }

s = 0
a = 1
b = 1
c = a+b

while c < 4000000
  s += c # 2, 10
  a = b+c # 3, 13
  b = a+c # 5, 21
  c = a+b # 8, 34...
end
puts s
